import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: "#f4f6fb",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 28,
    color: "#22223b",
    alignSelf: "center",
  },
  profileCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  profileInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#ececec",
  },
  label: {
    fontWeight: "bold",
    width: 90,
    color: "#3a3a40",
    fontSize: 16,
  },
  value: {
    flex: 1,
    color: "#4a4e69",
    fontSize: 16,
  },
  deleteContainer: {
    marginTop: 32,
    alignItems: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  modalView: {
    width: "85%",
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 28,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 8,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#22223b",
    textAlign: "center",
  },
  modalText: {
    textAlign: "center",
    marginBottom: 18,
    color: "#444",
    fontSize: 15,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#d1d1d6",
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
    fontSize: 16,
    backgroundColor: "#f8f8fa",
    color: "#22223b",
    flex: 1,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 12,
  },
});
